version: '3.8'

services:
  security-testing:
    build:
      context: .
      dockerfile: Dockerfile.security-testing
    container_name: security-testing-framework
    environment:
      - SECURITY_TEST_ENV=${SECURITY_TEST_ENV:-uat}
      - NODE_ENV=production
      - DEBUG=${DEBUG:-false}
    volumes:
      # Mount session files (if using local sessions)
      - ./jira-uat-session-*.json:/app/jira-uat-session-latest.json:ro
      # Mount reports directory for persistent storage
      - ./reports:/app/reports
      - ./logs:/app/logs
      # Mount configuration files
      - ./.env:/app/.env:ro
    networks:
      - security-network
    depends_on:
      - monitoring
    restart: unless-stopped
    mem_limit: 2g
    cpus: 1.0

  # Optional: Add monitoring service
  monitoring:
    image: prom/prometheus:latest
    container_name: security-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - security-network
    restart: unless-stopped

  # Optional: Add report server
  report-server:
    image: nginx:alpine
    container_name: security-reports
    ports:
      - "8080:80"
    volumes:
      - ./reports:/usr/share/nginx/html/reports:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - security-network
    restart: unless-stopped

networks:
  security-network:
    driver: bridge

volumes:
  reports-data:
  logs-data: 