# Nixpacks configuration for Railway
# Forces Railway to use latest dependencies

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[start]
cmd = "node dist/aoma-mesh-server.js"