name: Remote Smoke Checks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # hourly

permissions:
  contents: read

concurrency:
  group: remote-smoke
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      RAILWAY_BASE_URL: https://luminous-dedication-production.up.railway.app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Remote Health
        run: pnpm run remote:health

      - name: Remote Tools
        run: pnpm run remote:tools
