name: Remote Smoke Checks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # hourly

permissions:
  contents: read

concurrency:
  group: remote-smoke
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      RAILWAY_BASE_URL: https://luminous-dedication-production.up.railway.app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Remote Health
        run: pnpm run remote:health

      - name: Remote Tools
        run: pnpm run remote:tools

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "AOMA Mesh Remote Smoke FAILED - ${{ github.repository }} @ ${{ github.ref_name }}"
          to: "matt@mattcarpenter.com"
          from: ${{ secrets.SMTP_FROM }}
          html_body: true
          body: |
            <h3>AOMA Mesh Remote Smoke Checks FAILED</h3>
            <ul>
              <li>Repo: ${{ github.repository }}</li>
              <li>Branch: ${{ github.ref_name }}</li>
              <li>Workflow: ${{ github.workflow }}</li>
              <li>Run: <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Logs</a></li>
              <li>Production URL: ${{ env.RAILWAY_BASE_URL }}</li>
              <li>Timestamp (UTC): ${{ github.run_started_at }}</li>
            </ul>
